"""intial maingrat

Revision ID: 5b35a596dac4
Revises: b48f44b2847d
Create Date: 2026-03-23 18:41:29.333163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b35a596dac4'
down_revision = 'b48f44b2847d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=100), nullable=True))
        batch_op.drop_column('userfullname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userfullname', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###
