"""edit fullname to userfullname

Revision ID: dea4856be19d
Revises: 5b35a596dac4
Create Date: 2026-03-23 18:45:41.069134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea4856be19d'
down_revision = '5b35a596dac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userfullname', sa.String(length=100), nullable=True))
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('userfullname')

    # ### end Alembic commands ###
