"""initial migrate

Revision ID: 2be382771bab
Revises: 
Create Date: 2026-03-24 10:33:54.079756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2be382771bab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('fullusername')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullusername', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
